export const adminNav = [
  ["Dashboard", "/admin"],
  ["Siparişler", "/admin/siparisler"],
  ["Ürünler", "/admin/urunler"],
  ["Kategoriler", "/admin/kategoriler"],
  ["Varyantlar", "/admin/varyantlar"],
  ["Koleksiyonlar", "/admin/koleksiyonlar"],
  ["Stok", "/admin/stok"],
  ["Müşteriler", "/admin/musteriler"],
  ["Kampanyalar", "/admin/kampanyalar"],
  ["Kupon Kodları", "/admin/kuponlar"],
  ["Hediye/Paket", "/admin/hediye"],
  ["İçerik Yönetimi", "/admin/icerik"],
  ["Sayfalar", "/admin/sayfalar"],
  ["Blog", "/admin/blog"],
  ["Banner/Slider", "/admin/banner"],
  ["Popup", "/admin/popup"],
  ["Menüler", "/admin/menuler"],
  ["Tasarım", "/admin/tasarim"],
  ["Tema Ayarları", "/admin/tema"],
  ["Page Builder", "/admin/page-builder"],
  ["SEO", "/admin/seo"],
  ["Raporlar", "/admin/raporlar"],
  ["Entegrasyonlar", "/admin/entegrasyonlar"],
  ["Medya Kütüphanesi", "/admin/medya"],
  ["Kullanıcı Yönetimi", "/admin/kullanicilar"],
  ["Bildirimler", "/admin/bildirimler"],
  ["Ayarlar", "/admin/ayarlar"],
] as const;
